import random


def executa():
    print("Tabela A - Níveis 1 a 3")
    print("Tabela B - Níveis 4 a 6")
    print("Tabela C - Níveis 7 a 9")
    print("Tabela D - Níveis 10 a 12")
    print("Tabela E - Níveis 13 a 15")
    print("Tabela F - Níveis 16 a 18")
    print("Tabela G - Níveis 19 a 20")
    print("Tabela H - Tabela G nerfada")

    while True:
        escolha = (input("\nEscolha uma tabela: "))
        escolha = escolha.strip().upper()

        if escolha == "":
            break
        else:
            quantidade = int(input(f"\nUsando a Tabela {escolha}. Selecionar quantos items? "))
            for n in range(0, quantidade):
                rola_itens(tabelas[escolha])


def rola_itens(tabela):
    rolagem = random.randrange(0, len(tabela))
    print(tabela[rolagem])


a = ["Pergaminho de magia (truque)",
     "Poção de cura",
     "Pena de Quaal (âncora)",
     "Pergaminho de magia (nível 1)",
     "Filtro do amor",
     "Poção de veneno [AMALDIÇOADO]",
     "Elixir de saúde",
     "Unguento de Keoghtom (1 dose)",
     "Pergaminho de magia (nível 2)",
     "1d6 munição +1",
     "Poção de sopro de fogo",
     "Poção de cura maior",
     "Poção de escalar",
     "Poção de heroísmo",
     "Poção de invisibilidade",
     "Poção de ler mentes",
     "Poção de respirar na água",
     "Pergaminho de proteção",
     "Poção de amizade animal",
     "Pigmentos maravilhosos de Nolzur"]

b = ["Pergaminho de magia (nível 3)",
     "Pena de Quaal (leque)",
     "Pena de Quaal (chicote)",
     "Poção de encolher",
     "Poção de aumentar",
     "2d6 munição +1",
     "Pó do desaparecimento",
     "Colar de bolas de fogo (1 conta)",
     "Poção de forma gasosa",
     "Poção de resistência",
     "Solvente Universal",
     "Pergaminho de magia (nível 4)",
     "Bode de marfim (trabalho),"
     "Arma Viciosa",
     "1 munição +3",
     "Poção de velocidade",
     "Cola Soberana",
     "Trombeta da destruiçao",
     "Poção de cura superior",
     "Pó da seca (1d4 punhados)",
     "Pó de espirrar e tossir",
     "Unguento de Keoghtom (1d4+1 doses)",
     "Óleo escorregadio",
     "1d6 munição +2",
     "Armadura de adamante",
     "Elmo de compreensão de idiomas",
     "Poção de voo [PODEROSO]",
     "1d6 munição +3",
     "Flecha assassina",
     "1 Leão dourado",
     "Pergaminho de magia (nível 5)",
     "Pó da seca (1d6 punhados)",
     "Globo de fluxo",
     "Machado furioso [AMALDIÇOADO]",
     "Armadura de mitral",
     "Armadura de vulnerabilidade [AMALDIÇOADO]",
     "Tridente de comandar peixes",
     "1 Conta de força",
     "Gema elemental",
     "Poção de clarividência",
     "Poção de vitalidade",
     "Espada da vingança [AMALDIÇOADO]",
     "Arma +1",
     "Capa de respirar na água",
     "Garrafa da fumaça eterna",
     "Aljava de Ehlonna",
     "Pedra iônica (sustento)",
     "Bode de marfim (viagem)",
     "Anel de calor",
     "Espada do furto de vidas"]

c = ["2d6 munição +2",
     "Pedra iônica (proteção)",
     "Varinha do arcano de guerra +1",
     "Pergaminho de magia (nível 6)",
     "Poção de cura suprema",
     "Armadura +1 [PODEROSO]",
     "Escudo +1 [PODEROSO]",
     "Braçadeiras de arquearia",
     "Diadema da destruição",
     "Carrilhão de abertura",
     "Óculos noturnos",
     "Ferraduras do zéfiro",
     "Azagaia de relâmpago",
     "Armadura do marinheiro",
     "Colar de adaptação",
     "Corrente de contas de oração (destruir)",
     "Anel de andar na água",
     "Varinha de detectar magia",
     "Varinha de segredos",
     "Leque do vento",
     "---sword of sharpness---",
     "Armadura demoníaca [AMALDIÇOADO]",
     "---staff of the adder---",
     "Óleo de forma etérea",
     "Espada dançarina",
     "Couro batido encantador",
     "Luvas de nadar e escalar",
     "Sacola prestativa de Heward",
     "Flauta dos esgotos",
     "Corrente de contas de oração (abençoar)",
     "Corda de escalada",
     "Anel de queda suave",
     "Sela do cavaleiro",
     "Pedras de mensagem [PODEROSO]",
     "Cajado da píton",
     "Espada decepadora",
     "Marca congelante",
     "Pedra iônica (absorção)",
     "Adaga de envenenamento",
     "Botas élficas",
     "Olhos de visão momentânea",
     "Olhos de águia",
     "Anel de saltar",
     "Pergaminho de magia (nível 7)",
     "Algemas dimensionais",
     "Olhos do encantamento",
     "Luvas de apanhar projéteis",
     "Pedra iônica (agilidade)",
     "Pedra iônica (fortitude)",
     "Pedra iônica (intuição)"]

d = ["Pedra iônica (intelecto)",
     "Pedra iônica (liderança)",
     "Pedra iônica (força)",
     "Medalhão de pensamentos",
     "Cachorro de ônix",
     "Anel de natação",
     "Pena de Quaal (pássaro)",
     "Pena de Quaal (barco de cisne)",
     "Cajado de definhamento",
     "Óleo de precisão",
     "Robe dos itens úteis",
     "Manual do golens de barro",
     "Manual do golens de carne",
     "Manual do golens de ferro",
     "Manual do golens de pedra",
     "Manto de proteção [PODEROSO]",
     "Arco do juramento",
     "Anel de proteção [PODEROSO]",
     "Poção de invulnerabilidade",
     "Arma +2",
     "Mochila de carga",
     "Botas de levitação",
     "Botas de velocidade [PODEROSO]",
     "Brunea da escamas de dragão",
     "Malha élfica",
     "Pedra iônica (regeneração)",
     "Faixas de ferro de Bilarro",
     "Corrente de contas de oração (curar)",
     "Anel de cativar animais",
     "Corda de estrangulamento",
     "Varinha de detecção de inimigos",
     "Pedra da boa sorte",
     "Poção de força do gigante (role 1d6 para o tipo)",
     "2d6 munição +3",
     "Varinha do arcano de guerra +2",
     "Botas de caminhar e saltar",
     "Manto da aranha",
     "Manto élfico",
     "Língua flamejante",
     "Luvas do ladrão",
     "Gema da luminosidade",
     "Chapéu de disfarce",
     "Ferraduras da velocidade",
     "Bastão imóvel",
     "Lanterna de revelação",
     "Periapto de saúde",
     "Periapto de proteção contra veneno",
     "Periapto de cicatrização",
     "Anel de evasão",
     "Anel do aríete",
     "Corvo de prata",
     "Sandálias de patas de aranha",
     "Bastão do tentáculo",
     "Asas voadoras [PODEROSO]",
     "Pergaminho de magia (nível 8)",
     "Trombeta do Valhalla de prata",
     "Armadura +2 [PODEROSO]",
     "Escudo +2 [PODEROSO]",
     "Jarro de alquimia",
     "Escudo animado",
     "Armadura de resistência",
     "Escudo apanhador de flechas",
     "Cinto dos anões",
     "Braceletes de defesa",
     "Manto do morcego",
     "Mando da arraia",
     "Mosca de ébano [PODEROSO]",
     "Pedra iônica (armazenamento)",
     "Elefante de marfim",
     "Pérola do poder",
     "Flauta assombrada",
     "Anel de resistência",
     "Anel de visão de raio-x",
     "Robe das cores cintilantes",
     "Cimitarra da velocidade",
     "Escudo de atração de projéteis [AMALDIÇOADO]",
     "Baralho das ilusões",
     "Matador de gigantes",
     "Maça de destruição",
     "---brooch of shielding---",
     "Colar de bolas de fogo (1d6 contas)",
     "Amuleto de saúde",
     "Bacia de comandar elementais da água",
     "Brazeiro de comandar elementais do fogo",
     "Grifo de bronze [PODEROSO]",
     "Vassoura voadora [PODEROSO]",
     "Capa do saltimbanco",
     "Incensório de comandar elementais do ar",
     "Matadora de dragões",
     "Manoplas de força do ogro",
     "Tiara do intelecto",
     "Maça do rompimento",
     "Maça do terror",
     "Ladra das nove vidas",
     "Buraco portátil",
     "Coruja de serpentina [PODEROSO]",
     "Pedra de comandar elementais da terra",
     "Varinha de mísseis mágicos",
     "Varinha de teia",
     "Botas aladas [PODEROSO]"]

e = ["Trombeta de Valhalla de latão",
     "Armadura anã [PODEROSO]",
     "Poção de longevidade [PODEROSO]",
     "Dispositivo de Kwalish",
     "Botas do inverno",
     "Cinturão de força do gigante da colina",
     "Barco dobrável",
     "Anel de invisibilidade",
     "Manual de saúde corporal",
     "Manual do bom exercício",
     "Manual de rapidez de movimentos [PODEROSO]",
     "Tomo de liderança e influência",
     "Tomo da compreensão",
     "Tomo dos grandes pensamentos",
     "Cajado de trovão e relâmpago",
     "Varinha de obrigação",
     "Varinha de medo",
     "Pergaminho de magia (nível 9)",
     "Trombeta de Valhalla de bronze",
     "Cinturão de força do gigante de pedra/gelo",
     "Tapete voador [PODEROSO]",
     "Elmo de telepatia",
     "Pedra iônica (prontidão)",
     "Anel de regeneração [PODEROSO]",
     "Bastão do guardião de pactos +1 [PODEROSO]",
     "Cajado de enfeitiçar",
     "Lâmina do sol",
     "Cajado de cura",
     "Cinturão de força do gigante de fogo",
     "Trombeta de Valhalla de ferro",
     "Anel de estrelas cadentes",
     "Pedra iônica (maestria)",
     "Esfera de aniquilação [PODEROSO]",
     "Arma +3",
     "Cinturão de força do gigante das nuvens",
     "Cubo de força",
     "Martelo dos trovões",
     "Anel de escudo mental",
     "Bastão do guardião de pactos +2 [PODEROSO]",
     "Bastão de obediência/liderança",
     "Cajado do fogo",
     "Cajado de enxame de insetos",
     "Varinha de paralisia",
     "Anel de comandar elementais do fogo",
     "Armadura de invulnerabilidade [PODEROSO]",
     "Cinturão de força do gigante da tempestade",
     "Arremessador anão",
     "Espelho do aprisionamento",
     "Varinha das maravilhas",
     "Varinha do arcano de guerra +3"]

f = ["Amuleto de proteção contra detecção e localização",
     "Vela de invocação [PODEROSO]",
     "Malha do efreeti",
     "Bode de marfim (terror)",
     "Anel de ação livre",
     "Escudo sentinela",
     "Talismã da esfera",
     "Cajado de ataque",
     "Armadura +3 [PODEROSO]",
     "Escudo +3 [PODEROSO]",
     "Defensora [PODEROSO]",
     "Anel de armazenar magia",
     "Bastão de ressureição",
     "Espada vorpal",
     "Anel de comandar elementais da água",
     "Bastão de prontidão",
     "Cajado do frio",
     "Instrumento dos bardos - Bandolim de Fochlucan",
     "Instrumento dos bardos - Citara de Mac-Fuirmidh",
     "Bastão do grande poder",
     "Bastão do guardião de pactos +3 [PODEROSO]",
     "Instrumento dos bardos - Alaúde de Doss",
     "Bolsa de truques [PODEROSO]",
     "Instrumento dos bardos - Mandolim de Canaith",
     "Manto de resistência à magia",
     "Anel de refletir magias",
     "Robe dos olhos",
     "Tomo da língua quieta [ALERTA VERMELHO]",
     "Pedra iônica (absorção maior)",
     "Anel de comandar elementais da terra [PODEROSO]",
     "Gema de visão",
     "Corrente de contas de oração (auxiliar)",
     "Varinha de bolas de fogo",
     "Varinha de relâmpagos",
     "Varinha de metamorfose",
     "Robe do arquimago [PODEROSO]",
     "Elmo brilhante [PODEROSO]",
     "Instrumento dos bardos - Lira de Cli",
     "Anel de comandar elementais do ar [PODEROSO]",
     "Escaravelho da proteção",
     "---sword of answering---",
     "Cubo do portal [PODEROSO]",
     "Anel de invocação de djinni [PODEROSO]",
     "Cajado das florestas",
     "Armadura de placas da forma etérea",
     "Poço dos muitos mundos",
     "Bola de cristal [PODEROSO]",
     "Frasco de ferro (vazio) [PODEROSO]",
     "Bastão de absorção",
     "Escudo de proteção contra magia"]

g = ["Saco de feijões [PODEROSO]",
     "Manto de deslocamento",
     "Robe das estrelas",
     "Arma de alerta",
     "Talismã do mal absoluto",
     "Elmo de teletransporte [PODEROSO]",
     "Talismã da bondade pura",
     "Fortaleza instantânea de Daern [PODEROSO]",
     "Anel de telecinésia [PODEROSO]",
     "Manto de invisibilidade [PODEROSO]",
     "Bastão de segurança [PODEROSO]",
     "Cajado do poder [PODEROSO]",
     "Corsel de obsidiana [PODEROSO]",
     "Decantador de água infinita [PODEROSO]",
     "Amuleto dos planos [PODEROSO]",
     "Corrente de contas de oração (andar no vento)",
     "Instrumento dos bardos - Harpa de Anstruth",
     "Instrumento dos bardos - Harpa de Ollamh",
     "Cajado do arcano [PODEROSO]",
     "Corrente de contas de oração (invocar)",
     "Vingadora sagrada"
     "Baralho das surpresas [ALERTA VERMELHO]",
     "Frasco do efreeti [ALERTA VERMELHO]",
     "Anel dos três desejos [ALERTA VERMELHO]",
     "Lâmina da sorte [ALERTA VERMELHO]",
     "Poço dos muitos mundos [ALERTA VERMELHO]",
     "Machado dos lordes anões [ALERTA VERMELHO]",
     "Livro dos grandes feitos [ALERTA VERMELHO]",
     "Livro da escuridão perversa [ALERTA VERMELHO]",
     "Olho de Vecna [ALERTA VERMELHO]",
     "Mão de Vecna [ALERTA VERMELHO]",
     "Orbe dos dragões [ALERTA VERMELHO]",
     "Espada de Kas [ALERTA VERMELHO]",
     "Cetro de Orcus [ALERTA VERMELHO]"]

h = ["Manto de deslocamento",
     "Robe das estrelas",
     "Arma de alerta",
     "Talismã do mal absoluto",
     "Talismã da bondade pura",
     "Corrente de contas de oração (andar no vento)",
     "Instrumento dos bardos - Harpa de Anstruth",
     "Instrumento dos bardos - Harpa de Ollamh",
     "Corrente de contas de oração (invocar)",
     "Vingadora sagrada"]

tabelas = {"A": a, "B": b, "C": c, "D": d, "E": e, "F": f, "G": g, "H": h}

if __name__ == "__main__":
    executa()
